database:
  host: "localhost"
  port: 5432
  user: "panel"
  password: "panel@org!in"
  dbname: "panel"

jwt:
  secret: "portal.bosse"

server:
  port: 6969

smtp:
  host: "smtp.gmail.com"
  port: 587
  user: "aman7468051218@gmail.com"
  password: ""
  from: "B.O.S.S.E."

admin:
  email: "amanprasad7468@gmail.com"
  email1: ""
  email2: "info.eduecs@gmail.com"